'use client';

import { useState } from 'react';
import { FileText, Download } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { PageHeader } from '@/components/shared/page-header';
import { CurrencyDisplay } from '@/components/shared/currency-display';
import { EmptyState } from '@/components/shared/empty-state';
import { useMyPayslips, type PayrollEntry } from '@/features/payroll/api';
import { useCurrentUser } from '@/features/auth/api';

function formatCents(cents: number): string {
  return (cents / 100).toLocaleString('en-ET', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function printPayslip(entry: PayrollEntry, employeeName: string) {
  const w = window.open('', '_blank', 'width=600,height=800');
  if (!w) return;

  const html = `<!DOCTYPE html>
<html><head><title>Payslip</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 600px; margin: 2rem auto; color: #1a1a1a; }
  h1 { font-size: 1.5rem; margin-bottom: 0.25rem; }
  .meta { color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 1rem; }
  th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #e5e5e5; }
  th { font-size: 0.75rem; text-transform: uppercase; color: #666; background: #f9f9f9; }
  .amount { text-align: right; font-variant-numeric: tabular-nums; }
  .deduction { color: #dc2626; }
  .net-row { font-weight: 700; border-top: 2px solid #333; }
  .footer { margin-top: 2rem; font-size: 0.75rem; color: #999; text-align: center; }
  @media print { body { margin: 0; } .no-print { display: none; } }
</style>
</head><body>
  <h1>ETHR Payslip</h1>
  <div class="meta">${employeeName}</div>
  <table>
    <thead><tr><th>Description</th><th class="amount">Amount (ETB)</th></tr></thead>
    <tbody>
      <tr><td>Basic Salary</td><td class="amount">${formatCents(entry.basic_salary_cents)}</td></tr>
      <tr><td>Gross Pay</td><td class="amount">${formatCents(entry.gross_cents)}</td></tr>
      <tr><td>Income Tax</td><td class="amount deduction">-${formatCents(entry.income_tax_cents)}</td></tr>
      <tr><td>Employee Pension (7%)</td><td class="amount deduction">-${formatCents(entry.employee_pension_cents)}</td></tr>
      <tr><td>Employer Pension (11%)</td><td class="amount">${formatCents(entry.employer_pension_cents)}</td></tr>
      ${entry.other_deductions_cents > 0 ? `<tr><td>Other Deductions</td><td class="amount deduction">-${formatCents(entry.other_deductions_cents)}</td></tr>` : ''}
      <tr class="net-row"><td>Net Pay</td><td class="amount">${formatCents(entry.net_cents)}</td></tr>
    </tbody>
  </table>
  <div class="footer">Generated by ETHR &middot; This is a computer-generated document</div>
  <div class="no-print" style="text-align:center;margin-top:1rem">
    <button onclick="window.print()" style="padding:0.5rem 1.5rem;font-size:0.9rem;cursor:pointer;border:1px solid #ccc;border-radius:6px;background:#fff">
      Print / Save as PDF
    </button>
  </div>
</body></html>`;

  w.document.write(html);
  w.document.close();
}

export default function MyPayslipsPage() {
  const [page, setPage] = useState(1);
  const { data, isLoading } = useMyPayslips({ page });
  const { data: user } = useCurrentUser();

  return (
    <div className="space-y-6">
      <PageHeader title="My Payslips" description="View your salary breakdown by period" />

      {isLoading ? (
        <div className="grid gap-4 sm:grid-cols-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-40" />
          ))}
        </div>
      ) : !data?.data?.length ? (
        <EmptyState
          icon={FileText}
          title="No payslips yet"
          description="Your payslips will appear here after payroll is processed"
        />
      ) : (
        <div className="grid gap-4 sm:grid-cols-2">
          {data.data.map((entry) => (
            <Card key={entry.public_id}>
              <CardHeader className="pb-3">
                <div className="flex items-center justify-between">
                  <CardTitle className="text-base">Payslip</CardTitle>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => printPayslip(entry, user?.email ?? 'Employee')}
                  >
                    <Download className="h-4 w-4" />
                  </Button>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <Row label="Basic Salary" cents={entry.basic_salary_cents} />
                  <Row label="Gross" cents={entry.gross_cents} />
                  <div className="border-t pt-2">
                    <Row label="Income Tax" cents={entry.income_tax_cents} deduction />
                    <Row label="Employee Pension" cents={entry.employee_pension_cents} deduction />
                    {entry.other_deductions_cents > 0 && (
                      <Row label="Other Deductions" cents={entry.other_deductions_cents} deduction />
                    )}
                  </div>
                  <div className="border-t pt-2">
                    <div className="flex items-center justify-between">
                      <span className="text-sm font-semibold text-foreground">Net Pay</span>
                      <CurrencyDisplay cents={entry.net_cents} className="text-sm font-bold text-primary" />
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}

function Row({ label, cents, deduction }: { label: string; cents: number; deduction?: boolean }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-sm text-muted-foreground">{label}</span>
      <span className={`text-sm ${deduction ? 'text-red-500' : 'text-foreground'}`}>
        {deduction && '- '}
        <CurrencyDisplay cents={cents} />
      </span>
    </div>
  );
}
