[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000

; Production: ondemand to save memory when idle
pm = ondemand
pm.max_children = 40
pm.process_idle_timeout = 10s
pm.max_requests = 500
pm.status_path = /status

; Logging
access.log = /proc/self/fd/2
slowlog = /proc/self/fd/2
request_slowlog_timeout = 10s
