<?php

declare(strict_types=1);

use App\Enums\SubscriptionStatus;
use App\Enums\TenantStatus;
use App\Jobs\HandleOverdueInvoicesJob;
use App\Models\Invoice;
use App\Models\Plan;
use App\Models\Subscription;
use App\Models\Tenant;
use Illuminate\Support\Carbon;

/**
 * Dunning: what happens when a tenant stops paying.
 *
 * `HandleOverdueInvoicesJob` escalates in three tiers — remind at 7 days, mark
 * the subscription past-due at 30, suspend the tenant at 60. It suspends
 * customer accounts and had no test at all.
 *
 * Two of these tests document defects rather than desired behaviour, and say so
 * where they do. Both are written from the outside, using invoices shaped the
 * way `BillingService::generateMonthlyInvoice()` actually shapes them, because
 * the defects only appear when you do that rather than constructing an invoice
 * in whatever state the job happens to want.
 */
function overdueTenant(string $invoiceStatus, int $daysPastDue): array
{
    $tenant = createTenant(['status' => TenantStatus::ACTIVE]);
    $plan = Plan::factory()->create(['price_cents' => 100000]);

    $subscription = Subscription::factory()->create([
        'tenant_id' => $tenant->id,
        'plan_id' => $plan->id,
        'status' => SubscriptionStatus::ACTIVE,
    ]);

    $invoice = Invoice::create([
        'tenant_id' => $tenant->id,
        'subscription_id' => $subscription->id,
        'amount_cents' => 100000,
        'tax_cents' => 0,
        'total_cents' => 100000,
        'status' => $invoiceStatus,
        'line_items' => [],
        'due_date' => Carbon::today()->subDays($daysPastDue),
    ]);

    return [$tenant, $subscription, $invoice];
}

it('marks a sent invoice overdue after seven days', function () {
    [, , $invoice] = overdueTenant('sent', 10);

    (new HandleOverdueInvoicesJob)->handle();

    expect($invoice->refresh()->status)->toBe('overdue');
});

it('marks the subscription past due after thirty days', function () {
    [, $subscription, $invoice] = overdueTenant('sent', 35);

    (new HandleOverdueInvoicesJob)->handle();

    expect($invoice->refresh()->status)->toBe('past_due')
        ->and($subscription->refresh()->status)->toBe(SubscriptionStatus::PAST_DUE);
});

it('suspends the tenant after sixty days', function () {
    [$tenant] = overdueTenant('past_due', 70);

    (new HandleOverdueInvoicesJob)->handle();

    expect($tenant->refresh()->status)->toBe(TenantStatus::SUSPENDED);
});

it('leaves a paid invoice and its tenant alone', function () {
    [$tenant, $subscription, $invoice] = overdueTenant('paid', 90);

    (new HandleOverdueInvoicesJob)->handle();

    // Dunning must never touch a settled invoice. Suspending a paying customer
    // is the worst outcome available to this job.
    expect($invoice->refresh()->status)->toBe('paid')
        ->and($tenant->refresh()->status)->toBe(TenantStatus::ACTIVE)
        ->and($subscription->refresh()->status)->toBe(SubscriptionStatus::ACTIVE);
});

it('suspends a long-overdue invoice that was never escalated', function () {
    // The job missed the 7-30 and 30-60 windows entirely — which happens
    // whenever the scheduler stopped, the failure ethr:queue:check now watches
    // for. The invoice is 70 days past due and still `sent`.
    //
    // This used to escalate nowhere. Tiers 1 and 2 are bounded ABOVE (30 and 60
    // days), so both had aged out, and tier 3 matched only `overdue` and
    // `past_due` — so the tenant was never suspended, however long they went
    // without paying. Tier 3 now takes any unpaid status precisely because it is
    // the safety net and cannot assume the tiers before it ran.
    [$tenant, , $invoice] = overdueTenant('sent', 70);

    (new HandleOverdueInvoicesJob)->handle();

    expect($tenant->refresh()->status)->toBe(
        TenantStatus::SUSPENDED,
        'A 70-day-overdue invoice was never escalated because the job missed its earlier windows.'
    );
    expect($invoice->refresh()->status)->not->toBe('sent');
});

it('DEFECT: escalation never starts, because invoices are created as draft', function () {
    // BillingService::generateMonthlyInvoice() writes status => 'draft', and
    // nothing anywhere transitions an invoice to 'sent' — the only occurrences
    // of that string in app/ are this job's own queries.
    //
    // Tier 1 matches `status = 'sent'`. So no invoice generated by this system
    // ever enters dunning: nobody is reminded, no subscription is marked past
    // due, and no tenant is ever suspended for non-payment.
    //
    // This test asserts the CURRENT behaviour, not the desired behaviour, and
    // fails the day someone fixes it — which is the point. Whether a generated
    // invoice counts as "sent" is a billing-process decision for the owner, not
    // something to settle silently in a patch. See docs/audit/BASELINE.md §15d.
    [$tenant, $subscription, $invoice] = overdueTenant('draft', 90);

    (new HandleOverdueInvoicesJob)->handle();

    expect($invoice->refresh()->status)->toBe('draft')
        ->and($tenant->refresh()->status)->toBe(TenantStatus::ACTIVE)
        ->and($subscription->refresh()->status)->toBe(SubscriptionStatus::ACTIVE);
})->todo('Owner decision: should a generated invoice be `sent` on creation, or is there a send step?');
