/**
 * The canonical origin the public site is served from.
 *
 * `robots.ts`, `sitemap.ts` and `metadataBase` all need an absolute URL, and
 * Next has no way to know one at build time — these files are generated by the
 * build, not by a request, so there is no Host header to read.
 *
 * Read from `NEXT_PUBLIC_SITE_URL`, falling back to the apex. The fallback is
 * deliberately the real domain rather than localhost: getting this wrong in
 * development produces a sitemap nobody looks at, while getting it wrong in
 * production publishes canonical URLs pointing at a machine that is not the
 * site. One of those is recoverable.
 *
 * NOT derived from `NEXT_PUBLIC_ROOT_DOMAIN`, which `middleware.ts` uses for
 * tenant subdomain resolution: that is a bare hostname used for string
 * matching, and it is empty in single-host development (see the early return at
 * middleware.ts:31). Reusing it would make the sitemap disappear exactly where
 * the tenancy model is switched off.
 */
export const SITE_URL: string = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://ethr.et"
).replace(/\/$/, "");

/** The public marketing routes, and the only ones a crawler should index. */
export const PUBLIC_ROUTES = [
  "/",
  "/features",
  "/pricing",
  "/faq",
  "/contact",
  "/privacy",
  "/terms",
] as const;
