import { AVAILABLE_LOCALES, localeHref } from "@/lib/i18n/config";

/**
 * The canonical origin the public site is served from.
 *
 * `robots.ts`, `sitemap.ts` and `metadataBase` all need an absolute URL, and
 * Next has no way to know one at build time — these files are generated by the
 * build, not by a request, so there is no Host header to read.
 *
 * Read from `NEXT_PUBLIC_SITE_URL`, falling back to the apex. The fallback is
 * deliberately the real domain rather than localhost: getting this wrong in
 * development produces a sitemap nobody looks at, while getting it wrong in
 * production publishes canonical URLs pointing at a machine that is not the
 * site. One of those is recoverable.
 *
 * NOT derived from `NEXT_PUBLIC_ROOT_DOMAIN`, which `middleware.ts` uses for
 * tenant subdomain resolution: that is a bare hostname used for string
 * matching, and it is empty in single-host development (see the early return at
 * middleware.ts:31). Reusing it would make the sitemap disappear exactly where
 * the tenancy model is switched off.
 */
export const SITE_URL: string = (
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://ethr.et"
).replace(/\/$/, "");

/** The public marketing routes, and the only ones a crawler should index. */
export const PUBLIC_ROUTES = [
  "/",
  "/features",
  "/pricing",
  "/faq",
  "/contact",
  "/privacy",
  "/terms",
] as const;

/**
 * `canonical` plus the `hreflang` set for one public page, in one locale.
 *
 * Every public page now exists twice — `/am/pricing` and `/en/pricing` — and
 * two URLs carrying the same content is precisely what a search engine treats
 * as duplication unless they declare each other. `languages` emits the
 * `<link rel="alternate" hreflang>` pair, and `x-default` points at the
 * unprefixed URL, which is the redirector that negotiates per visitor. That is
 * exactly what `x-default` is specified for: the page to send a reader to when
 * none of the listed languages is a better match than the site's own choice.
 *
 * Paths are relative; Next resolves them against `metadataBase`.
 *
 * `locale` is `null` for the unprefixed redirectors, whose canonical is
 * themselves — they are the x-default, so pointing their canonical at one of
 * the two languages would tell a crawler that `/` *is* the Amharic page.
 */
export function alternatesFor(path: string, locale: string | null) {
  return {
    canonical: locale ? localeHref(locale, path) : path,
    languages: {
      ...Object.fromEntries(
        AVAILABLE_LOCALES.map((code) => [code, localeHref(code, path)]),
      ),
      "x-default": path,
    },
  };
}
