<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Invoice Receipt — {{ $invoice->public_id }}</title>
<style>
  body { font-family: DejaVu Sans, Arial, sans-serif; color: #1a1a2e; font-size: 12px; margin: 0; padding: 0; }
  .page { padding: 40px; }
  .header { display: flex; justify-content: space-between; margin-bottom: 32px; }
  .brand { font-size: 22px; font-weight: 700; color: #2563eb; }
  .brand-sub { font-size: 11px; color: #6b7280; margin-top: 2px; }
  .badge { background: #dcfce7; color: #166534; padding: 3px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  h2 { font-size: 18px; margin: 0 0 4px; }
  .meta { color: #6b7280; font-size: 11px; }
  .section-title { font-weight: 600; font-size: 11px; text-transform: uppercase; color: #9ca3af; letter-spacing: 0.05em; margin-bottom: 8px; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin-top: 4px; }
  th { text-align: left; padding: 8px; background: #f3f4f6; font-size: 11px; font-weight: 600; color: #374151; }
  td { padding: 8px; border-bottom: 1px solid #e5e7eb; font-size: 12px; }
  .amount { text-align: right; }
  .total-row td { font-weight: 700; border-top: 2px solid #374151; border-bottom: none; }
  .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
  .two-col { display: flex; gap: 32px; }
  .two-col > div { flex: 1; }
</style>
</head>
<body>
<div class="page">
  <div class="header">
    <div>
      <div class="brand">ETHR</div>
      <div class="brand-sub">Ethiopian Workforce Operating System</div>
    </div>
    <div style="text-align:right">
      <h2>RECEIPT</h2>
      <div class="meta">{{ $invoice->public_id }}</div>
      @if($invoice->paid_at)
      <div style="margin-top:6px"><span class="badge">PAID</span></div>
      @endif
    </div>
  </div>

  <div class="two-col">
    <div>
      <div class="section-title">Billed To</div>
      <div style="font-weight:600">{{ $tenant->name }}</div>
      <div class="meta">{{ $tenant->subdomain }}.ethr.et</div>
    </div>
    <div>
      <div class="section-title">Invoice Details</div>
      <table>
        <tr>
          <td class="meta">Invoice Date</td>
          <td>{{ $invoice->created_at->format('d M Y') }}</td>
        </tr>
        <tr>
          <td class="meta">Due Date</td>
          <td>{{ $invoice->due_date?->format('d M Y') ?? '—' }}</td>
        </tr>
        @if($invoice->paid_at)
        <tr>
          <td class="meta">Paid On</td>
          <td>{{ \Carbon\Carbon::parse($invoice->paid_at)->format('d M Y') }}</td>
        </tr>
        @endif
      </table>
    </div>
  </div>

  <div class="section-title" style="margin-top:32px">Line Items</div>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th class="amount">Amount</th>
      </tr>
    </thead>
    <tbody>
      @foreach($line_items as $item)
      <tr>
        <td>{{ $item['description'] ?? '—' }}</td>
        <td class="amount">{{ number_format(($item['amount_cents'] ?? 0) / 100, 2) }} ETB</td>
      </tr>
      @endforeach
      @if(empty($line_items))
      <tr>
        <td>{{ $invoice->description ?? 'Subscription' }}</td>
        <td class="amount">{{ number_format(($invoice->amount_cents ?? 0) / 100, 2) }} ETB</td>
      </tr>
      @endif
    </tbody>
    <tfoot>
      <tr class="total-row">
        <td>Total</td>
        <td class="amount">{{ number_format(($invoice->total_cents ?? $invoice->amount_cents ?? 0) / 100, 2) }} ETB</td>
      </tr>
    </tfoot>
  </table>

  <div class="footer">
    Generated by ETHR — Ethiopian Workforce Operating System &bull; support@ethr.et
  </div>
</div>
</body>
</html>
